apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: clafhm480-python 
  janus-idp.io/tekton: clafhm480-python
  backstage.io/kubernetes-id: clafhm480-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: clafhm480-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml