apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: clafhm480-python
  janus-idp.io/tekton: clafhm480-python
  backstage.io/kubernetes-id: clafhm480-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: clafhm480-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
